### ISSUE TITLE
Why don't have SetPosition() for box2d.Body?

### ISSUE THREAD

**Issue by SteveCruise** [ByteArena/box2d#29]
`fixture.GetBody().SetPosition(box2d.MakeB2Vec2(0, 0))`

**Comment by SteveCruise** [comment]
I got `SetTransform()`, Thank you.

**Comment by xtuc** [comment]
does it address your issue? can we close this?

**Comment by SteveCruise** [comment]
@xtuc Ok, I am just waiting a sure.
