### ISSUE TITLE
Simulation instability caused by some joints

### ISSUE THREAD

**Issue by maxfish** [ByteArena/box2d#9]
It looks like some of the joints types don't work properly.

I'm implementing a loader for R.U.B.E scenes here https://github.com/maxfish/gojira2d/blob/master/pkg/physics/b2djson_scene.go and I'm trying a lot of different scenes.
I can see that the only joints which work well are revolute, rope, distance and wheel. Motor, prismatic, weld and friction seem to make the simulation explode after a while.

Here is one example of a weld join that is unstable: https://pastebin.com/dPB2xBfV
As soon as body3, while falling, touches body2, body2 sprints away from the screen at high speed

Another example simulating a R.U.B.E scene containing all types of joints:
- This is how it's supposed to be https://www.youtube.com/watch?v=X6Unn3ybcKI
- This is how the Box2D implementation simulate it https://www.youtube.com/watch?v=1wUdmBTDKLI

Any ideas of what could be the cause?

**Comment by maxfish** [comment]
Found a code error for the Prismatic joints when warmStart is true. I've fixed it in my fork https://github.com/maxfish/box2d/commit/a623c1c17307645c2d47ba55875056de0776956f

**Comment by xtuc** [comment]
Nice! would you mind doing a PR?

**Comment by maxfish** [comment]
Here it is #10 
Unfortunately, the other issues are still there. I'll keep checking

**Comment by maxfish** [comment]
After the fixes I've submitted via PRs (including the changes suggested in #7), it looks like the joints (weld, revolute, prismatic, friction, motor, distance, rope, wheel) work as expected.

Here there is an updated video: https://youtu.be/zo81uKfpTzQ

**Comment by maxfish** [comment]
I'm closing this since the issue seems to be fixed now
